name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  ## What's Changed
  $CHANGES

categories:
  - title: '### Features'
    labels:
      - 'feature'
  - title: '### Bug Fixes'
    labels:
      - 'bug'
  - title: '### Documentation'
    labels:
      - 'documentation'
  - title: '### Refactoring'
    labels:
      - 'refactoring'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: minor

autolabeler:
  - label: 'feature'
    title:
      - '/feat|feature/i'
  - label: 'bug'
    title:
      - '/fix|bug/i'
  - label: 'documentation'
    files:
      - '*.md'
  - label: 'refactoring'
    title:
      - '/refactor/i'